---
title: "Tema 3 apuntes"
author: "Viacheslav Shalisko"
date: "5 de junio de 2019"
output: html_document
self_contained: TRUE
---

## Apuntes para tema 3

```{r}
a <- 1:10
a
b <- c(1.0, -3.4, 2, 140.1)
b

typeof(a)
typeof(b)

c <- c("lunes", "martes", "miercoles", "jueves", "viernes")
c
d <- c(TRUE, FALSE, FALSE, TRUE)
d


typeof(c)
typeof(d)
```


```{r}
c(a, b)
c(a,b,c)
c(a,b,c,d)
c(a,d)
```

```{r}
e <- c("masculino", "femenino", "masculino", "neutro", "femenino")
typeof(e)
e.fact <- as.factor(e)
levels(e.fact)
e.fact
typeof(e.fact)
class(e.fact)
```

```{r}
m1 <- matrix(1:12, nrow = 3, ncol = 4)
m1
m2 <- matrix(runif(9,0,10), nrow = 3, ncol = 3)
m2
dim(m1)
dim(m2)

cbind(m1,m2)
```

```{r}
ciudades.df <- data.frame(
  "id" = 1:4, 
  "nombre" = c("Ciudad de México (ZMCM)", "Guadalajara (AMG)", "Monterrey (ZMM)", "León"), 
  "tipo" = as.factor(c("megaciudad","ciudad","ciudad","ciudad")),
  "poblacion" = c(20.40, 4.75, 4.69, 1.24),
  "latitud" = c(19.428, 20.667, 25.6714, 21.129),
  "longitud" = c(-99.128, -103.392, -100.309, -101.674),
  stringsAsFactors = FALSE
)

dim(ciudades.df)
names(ciudades.df)
row.names(ciudades.df)
str(ciudades.df)


ciudades.df
```

```{r}
mi_vector <- 1:10
mi_factor <- as.factor(c("F1","F2"))
mi_matriz <- matrix(1:6, nrow = 2)
mi_df     <- data.frame("var_num" = 0:2, "var_text" = c("uno", "dos", "tres"))

mi_lista <- list("un_vector" = mi_vector, "un_factor" = mi_factor, "una_matriz" = mi_matriz, "un_df" = mi_df)
mi_lista

str(mi_lista)

length(mi_lista)
```

```{r}
meses <- c("enero", "febrero", "marzo", "abril",
           "mayo", "junio", "julio", "agosto",
           "septiembre", "octubre", "noviembre", "diciembre")

```

```{r}
meses[3] 	
meses[2:5] 
meses[5:2]
meses[c(1,6,12)]
meses.selectos <- meses[7:9]
meses.selectos
meses[15]
```

```{r}
m2

m2[2,3] 
m2[1,] 
m2[,2] 
m2[c(1,3),2]
m2[c(1,3),1:2]
```

```{r}
mi_lista[3]
mi_lista[[3]]
mi_lista["una_matriz"]
mi_lista[c("una_matriz","un_df")]  
mi_lista$una_matriz
mi_lista$una_matriz[2,3]

```


```{r}
ciudades.df[2]
ciudades.df[2:4]
ciudades.df["nombre"] 
ciudades.df[["nombre"]]
#ciudades.df[[c("nombre", "poblacion")]]
ciudades.df$nombre 

ciudades.df[,2]
ciudades.df[2,]


ciudades.df[,c("nombre", "poblacion")]
ciudades.df[1,c("nombre", "poblacion")]

```

