---
title: "Practica 8"
author: "Viacheslav Shalisko"
date: "31 de octubre de 2017"
output: html_document
---

## Ejercicio 1

```{r}
library(maptools)
```


```{r fig.width=12, fig.height=10, cache = TRUE}

ruta_estados <- 'datos/Estados.shp'

estados <- readShapePoly(ruta_estados)

palette(topo.colors(32))
plot(estados, axes = TRUE, border = "red", 
     col = estados$NOM_ENT, main = "Estados y Municipios de México")

legend("bottomleft", fill = palette(topo.colors(32)), 
       legend = levels(estados$NOM_ENT),
       bty = "n", cex = 0.7)

ruta_municipios <- 'datos/Municipios.shp'
municipios <- readShapePoly(ruta_municipios)

plot(municipios, add = TRUE)


```

## Ejercicio 2

```{r fig.width=12, fig.height=10}
mi_crs_lcc <- CRS("+proj=lcc +lat_1=17.5 +lat_2=29.5 +lat_0=12 +lon_0=‐102 +x_0=2500000 +y_0=0 +units=m +ellps=GRS80 +datum=WGS84")

ruta_estados <- 'datos/Estados.shp'

estados <- readShapePoly(ruta_estados, proj4string = mi_crs_lcc)

palette(gray.colors(32))
plot(estados, axes = TRUE, border = "gray", 
     col = estados$NOM_ENT, main = "Estados de México")

lista_lat <- c(20.65, 19.41)
lista_lon <- c(-103.35, -99.13)
puntos <- data.frame(lista_lon, lista_lat)
names(puntos) <- c("Longitud", "Latitud")

mi_crs <- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")

puntos_sp <- SpatialPoints(puntos, proj4string = mi_crs)

puntos_sp

puntos_lcc <- spTransform(puntos_sp, mi_crs_lcc)

puntos_lcc

plot(puntos_lcc, add = TRUE, pch = 19, cex = 1.5, col = "red")


```

## Ejercicio 3

```{r fig.width=12, fig.height=10}
ruta_raster <- 'datos/GMTED2010_075_Cotoplaxi.tif'

library(raster)

mi_raster <- raster(ruta_raster)

mi_raster

plot(mi_raster)


library(rworldmap)
world_high <- getMap(resolution = "low")
plot(world_high, add=TRUE)

```



