---
title: "Practica 7"
author: "Viacheslav Shalisko"
date: "24 de octubre de 2017"
output: html_document
---

## Ejercicio 1

```{r}
mi_variable <- c(10,13,7,5,7,1,1,3,3,10,14)

summary(mi_variable)
boxplot(mi_variable)
hist(mi_variable, breaks=14, col="gray")
```

## Ejercicio 2
#### Precipitación por meses

```{r fig.width=10}
mi_tabla <- read.csv("Prec.csv")

dim(mi_tabla)
head(mi_tabla)
summary(mi_tabla)
boxplot(mi_tabla[,2:13])
```

```{r}
mis_promedios <- apply(mi_tabla[,2:13],2,FUN = mean)
mis_promedios

barplot(mis_promedios, col=c("yellow","pink"), 
        main="Promedios de preciciptación por mes",
        ylab="Precipitación en mm")
  
  
```

## Ejercicio 3
#### Mapas básicas (modulo *maps*)

```{r fig.width=10}
library(maps)
library(mapproj)

map('world', fill=TRUE, col=2:7)

map('world', fill=TRUE, col=2:7, projection = "globular")
my_grid <- map('world', plot = FALSE)
map.grid(my_grid)

```

## Ejercicio 4
#### Mapa de México y Centroamérica

```{r fig.width=10}
ext_vector <- c(-107,-72,6,24)

my_map <- map('world', border = "darkgray", fill = TRUE,
              col = c("lightgreen","lightyellow","lightblue","coral","tan"),
              xlim = ext_vector[1:2], ylim = ext_vector[3:4])

map.axes(cex.axis = 0.9)
map.scale(ratio = FALSE)
title("Centroamérica y sur de Méxco")

map('lakes', add = TRUE, fill = TRUE, col = "royalblue", border = "blue")

my_names <- my_map$names
my_good_names <- my_names[!grepl(":+", my_names)]
map.text('world', regions = my_good_names, exact = TRUE, cex = 0.85, add = TRUE)

```


