---
title: "Georriesgos pruebas 1"
author: "Viacheslav Shalsiko"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(sp)
library(rgdal)
library(leaflet)
```

```{r}
hexagonos <- rgdal::readOGR("MallaHexagonos/MallaHexagonos_GEO_JSON.geojson")
inundaciones <- rgdal::readOGR("MallaHexagonos/ZonasInundacion_GEO_JSON.geojson")
#hexagonos_raw <- topoData <- readLines("hexagonos_ver1_seleccion_geo_JSON.geojson") %>% paste(collapse = "\n") 

str(hexagonos@data)

hexagonos@data["Eventos"][hexagonos@data["Eventos"] == '1 evento'] <- '1'
hexagonos@data$Eventos <- factor(hexagonos@data$Eventos, ordered = TRUE,
                                    levels = c('1', '2 a 5', '6 a 9', '10 a 30', 'Mas de 30'))
levels(hexagonos@data$Eventos)
#hexagonos@data$Eventos_int <- as.numeric(hexagonos@data$Eventos)


hexagonos@data$random <- runif(n = dim(hexagonos@data)[1])

str(inundaciones@data)

```


```{r fig.width = 8, fig.height = 7}
mi_paleta <- c("darkgreen", "lightgreen", "yellow", "red", "darkred")
mi_paleta_continua <- colorRampPalette(mi_paleta)
pal <- colorFactor(mi_paleta_continua(5), NULL)

pal_viridis <- colorNumeric("viridis", NULL)

mapa1 <- leaflet()
mapa1 <- addTiles(mapa1)
mapa1 <- setView(mapa1, lng=-103.35, lat=20.7, zoom=12)

## agregar poligonos SP
mapa1 <- addPolygons(mapa1, data = hexagonos, color = "#444444", 
                     weight = 0.5, smoothFactor = 0.5, 
                     opacity = 1.0, fillOpacity = 0.5,
                     fillColor = ~pal(Eventos),
                     highlightOptions = highlightOptions(color = "white", 
                                      weight = 2, bringToFront = TRUE),
                     #label = ~paste0("Eventos: ", Eventos),
                     #popup = ~paste0("Eventos: ",Eventos,"</br>Mas informaci贸n: <a href=", Eventos, ">", formatC(10000*random, big.mark = ","), "</a>")
                     popup = ~paste0("Eventos: ",Eventos),
                     group = "inundaciones"
                     )

mapa1 <-addPolygons(mapa1, data = inundaciones, color = "#777777",
                    weight = 0.5, smoothFactor = 0.5,
                    opacity = 1.0, fillOpacity = 0.5,
                    fillColor = "red",
                    highlightOptions = highlightOptions(color = "white", 
                                      weight = 2, bringToFront = TRUE),
                    popup = ~paste0("Zona: ",Pass),
                    group = "zonas de mayor riesgo de inundaci贸n"
                    )

mapa1 <- addLayersControl(mapa1,
                        baseGroups = c("zonas de mayor riesgo de inundaci贸n",
                                       "inundaciones"),
                        #overlayGroups = c("leyenda"),
                        options = layersControlOptions(collapsed = FALSE)
                        )

mapa1 <- addLegend(mapa1,
                  #group = "leyenda",
                  group = "inundaciones",
                  className = "info legend inundaciones",
                  position = "topright",
                  title = c("Inundaciones hist贸ricas:<br><em>eventos registrados</em>"),
                  colors = mi_paleta,
                  labels = levels(hexagonos@data$Eventos)[1:5],
                  opacity = 0.6)

mapa1 <- htmlwidgets::onRender(mapa1,"
    function(el, x) {
      var updateLegend = function () {
          var selectedGroup = document.querySelectorAll('input:checked')[0].nextSibling.innerText.substr(1);

          document.querySelectorAll('.legend').forEach(a => a.hidden=true);
          document.querySelectorAll('.legend').forEach(l => {
            if (l.classList.contains(selectedGroup)) l.hidden=false;
          });
      };
      updateLegend();
      this.on('baselayerchange', el => updateLegend());
    }")

## trabajar con JSON fuente
#mapa1 <- addGeoJSON(mapa1, geojson = hexagonos_raw, 
#                    weight = 1, color = "#444444", fill = FALSE)


mapa1
```

