---
title: "Actividad 2"
author: "Viacheslav Shalsiko"
date: "`r Sys.Date()`"
output: html_document
---

## Preparar el entorno

```{r}
library(sf)
library(raster)
sessionInfo()
```

## Cargar capas de datos fuente

```{r cache=TRUE}
estaciones <- st_read("datos/Estaciones_SMN_alt.shp")
estados <- st_read("datos/Estados.shp")
```

## Consultar tabla de atributos de archivos fuente

```{r cache=TRUE}
summary(estados)
knitr::kable(estados)

mi_estado <- estados[estados$NOM_ENT == "Nayarit",]
knitr::kable(mi_estado)

summary(estaciones)

mis_estaciones <- estaciones[estaciones$CVE_ENT == "18",]
knitr::kable(mis_estaciones)
```

## Visualizar los puntos y estado

```{r cache=TRUE}
plot(st_geometry(mi_estado), border="black")
plot(st_geometry(mis_estaciones), pch=23, bg="gray")

estados_geo <- st_transform(estados, crs=st_crs(estaciones))
estados_geo

plot(st_geometry(mis_estaciones), pch=23, bg=c("yellow","blue"))
plot(st_geometry(estados_geo), border="black", add=TRUE)

text(x = -105, y = 22, labels = "Nayarit", 
     pos = 3, col = "black", cex = 1.1)
```

## Configurar vista de etiquetas de estados en México

```{r}
# buscamos centroides de los estados de México
centroides <- st_centroid(estados_geo)
centroides

plot(st_geometry(estados_geo), border="darkgray")
text(x = st_coordinates(centroides)[,1],
     y = st_coordinates(centroides)[,2],
     labels = as.character(estados_geo$NOM_ENT),
     pos = 3, offset = 0.4, col = "black", cex = 0.6)
```

## Construir un rectangulo para recorte de datos en la zona de estado de interés

```{r}
mi_estado_geo <- st_transform(mi_estado, crs=st_crs(estaciones))
mi_estado_bufer <- st_buffer(mi_estado_geo, dist = 30000)
caja <- st_bbox(mi_estado_bufer)
caja

rectangulo <- st_as_sfc(caja, crs=st_crs(estaciones))
rectangulo

plot(st_geometry(rectangulo), border="red")
plot(st_geometry(mi_estado_bufer), border="orange", add=TRUE)
plot(st_geometry(mi_estado_geo), add=TRUE)
plot(st_geometry(mis_estaciones), pch=23, bg="gray", add=TRUE)
```

## Leer capa de datos raster

```{r cache=TRUE}
MDE <- raster("datos/MDE_Nayarit.tif")
MDE

mis_colores <- rev(hcl.colors(n = 20, pal = "RdYlBu", alpha = 0.9))

plot(MDE, col = mis_colores)

rectangulo_sp <- as(rectangulo, "Spatial")
MDE_recorte <- crop(MDE, rectangulo_sp)

plot(MDE_recorte, col = mis_colores)
```

## Generar relieve sombreado

```{r cache=TRUE}
pendiente <- terrain(MDE_recorte, "slope")
orientacion <- terrain(MDE_recorte, "aspect")
sombreado <- hillShade(slope=pendiente,
                       aspect=orientacion,
                       angle=20,
                       direction=30)

sombreado
plot(sombreado)
```

## Mapa resultante

```{r}
colores_transparentes <- rev(hcl.colors(n=20,
                                        pal="RdYlBu",
                                        alpha=0.5))
MDE_recorte_t <- terra::rast(MDE_recorte)
sombreado_t <- terra::rast(sombreado)

plot(MDE_recorte_t,
     col=colores_transparentes,
     asp=1,
     main="Estaciones en Nayarit")
plot(sombreado_t, add=TRUE,
     col=hcl.colors(n=20, pal="Grays"),
     legend=FALSE)
plot(MDE_recorte_t, add=TRUE,
     col=colores_transparentes,
     legend=FALSE)
plot(st_geometry(estados_geo), border="gray30", add=TRUE)
plot(st_geometry(mi_estado_geo), border="black", add=TRUE)
plot(st_geometry(mis_estaciones), pch=21, bg="yellow", add=TRUE)
text(
  x = st_coordinates(centroides)[,1],
  y = st_coordinates(centroides)[,2],
  labels=as.character(estados_geo$NOM_ENT),
  pos=3, offset=0.8, col="black", cex=1.2
)
```
